// Code generated by protoc-gen-entgrpc. DO NOT EDIT.
package entpb

import (
	context "context"
	base64 "encoding/base64"
	entproto "entgo.io/contrib/entproto"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	fmt "fmt"
	ent "github.com/KasumiMercury/uo-patradb-dogtrot/ent"
	channel "github.com/KasumiMercury/uo-patradb-dogtrot/ent/channel"
	video "github.com/KasumiMercury/uo-patradb-dogtrot/ent/video"
	empty "github.com/golang/protobuf/ptypes/empty"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// ChannelService implements ChannelServiceServer
type ChannelService struct {
	client *ent.Client
	UnimplementedChannelServiceServer
}

// NewChannelService returns a new ChannelService
func NewChannelService(client *ent.Client) *ChannelService {
	return &ChannelService{
		client: client,
	}
}

// toProtoChannel transforms the ent type to the pb type
func toProtoChannel(e *ent.Channel) (*Channel, error) {
	v := &Channel{}
	channel_id := e.ChannelID
	v.ChannelId = channel_id
	display_name := e.DisplayName
	v.DisplayName = display_name
	handle := e.Handle
	v.Handle = handle
	id := e.ID
	v.Id = id
	thumbnail_url := e.ThumbnailURL
	v.ThumbnailUrl = thumbnail_url
	for _, edg := range e.Edges.Videos {
		id := edg.ID
		v.Videos = append(v.Videos, &Video{
			Id: id,
		})
	}
	return v, nil
}

// toProtoChannelList transforms a list of ent type to a list of pb type
func toProtoChannelList(e []*ent.Channel) ([]*Channel, error) {
	var pbList []*Channel
	for _, entEntity := range e {
		pbEntity, err := toProtoChannel(entEntity)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		pbList = append(pbList, pbEntity)
	}
	return pbList, nil
}

// Create implements ChannelServiceServer.Create
func (svc *ChannelService) Create(ctx context.Context, req *CreateChannelRequest) (*Channel, error) {
	channel := req.GetChannel()
	m, err := svc.createBuilder(channel)
	if err != nil {
		return nil, err
	}
	res, err := m.Save(ctx)
	switch {
	case err == nil:
		proto, err := toProtoChannel(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return proto, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Get implements ChannelServiceServer.Get
func (svc *ChannelService) Get(ctx context.Context, req *GetChannelRequest) (*Channel, error) {
	var (
		err error
		get *ent.Channel
	)
	id := req.GetId()
	switch req.GetView() {
	case GetChannelRequest_VIEW_UNSPECIFIED, GetChannelRequest_BASIC:
		get, err = svc.client.Channel.Get(ctx, id)
	case GetChannelRequest_WITH_EDGE_IDS:
		get, err = svc.client.Channel.Query().
			Where(channel.ID(id)).
			WithVideos(func(query *ent.VideoQuery) {
				query.Select(video.FieldID)
			}).
			Only(ctx)
	default:
		return nil, status.Error(codes.InvalidArgument, "invalid argument: unknown view")
	}
	switch {
	case err == nil:
		return toProtoChannel(get)
	case ent.IsNotFound(err):
		return nil, status.Errorf(codes.NotFound, "not found: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Update implements ChannelServiceServer.Update
func (svc *ChannelService) Update(ctx context.Context, req *UpdateChannelRequest) (*Channel, error) {
	channel := req.GetChannel()
	channelID := channel.GetId()
	m := svc.client.Channel.UpdateOneID(channelID)
	channelChannelID := channel.GetChannelId()
	m.SetChannelID(channelChannelID)
	channelDisplayName := channel.GetDisplayName()
	m.SetDisplayName(channelDisplayName)
	channelHandle := channel.GetHandle()
	m.SetHandle(channelHandle)
	channelThumbnailURL := channel.GetThumbnailUrl()
	m.SetThumbnailURL(channelThumbnailURL)
	for _, item := range channel.GetVideos() {
		videos := item.GetId()
		m.AddVideoIDs(videos)
	}

	res, err := m.Save(ctx)
	switch {
	case err == nil:
		proto, err := toProtoChannel(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return proto, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Delete implements ChannelServiceServer.Delete
func (svc *ChannelService) Delete(ctx context.Context, req *DeleteChannelRequest) (*empty.Empty, error) {
	var err error
	id := req.GetId()
	err = svc.client.Channel.DeleteOneID(id).Exec(ctx)
	switch {
	case err == nil:
		return &emptypb.Empty{}, nil
	case ent.IsNotFound(err):
		return nil, status.Errorf(codes.NotFound, "not found: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// List implements ChannelServiceServer.List
func (svc *ChannelService) List(ctx context.Context, req *ListChannelRequest) (*ListChannelResponse, error) {
	var (
		err      error
		entList  []*ent.Channel
		pageSize int
	)
	pageSize = int(req.GetPageSize())
	switch {
	case pageSize < 0:
		return nil, status.Errorf(codes.InvalidArgument, "page size cannot be less than zero")
	case pageSize == 0 || pageSize > entproto.MaxPageSize:
		pageSize = entproto.MaxPageSize
	}
	listQuery := svc.client.Channel.Query().
		Order(ent.Desc(channel.FieldID)).
		Limit(pageSize + 1)
	if req.GetPageToken() != "" {
		bytes, err := base64.StdEncoding.DecodeString(req.PageToken)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "page token is invalid")
		}
		pageToken := string(bytes)
		listQuery = listQuery.
			Where(channel.IDLTE(pageToken))
	}
	switch req.GetView() {
	case ListChannelRequest_VIEW_UNSPECIFIED, ListChannelRequest_BASIC:
		entList, err = listQuery.All(ctx)
	case ListChannelRequest_WITH_EDGE_IDS:
		entList, err = listQuery.
			WithVideos(func(query *ent.VideoQuery) {
				query.Select(video.FieldID)
			}).
			All(ctx)
	}
	switch {
	case err == nil:
		var nextPageToken string
		if len(entList) == pageSize+1 {
			nextPageToken = base64.StdEncoding.EncodeToString(
				[]byte(fmt.Sprintf("%v", entList[len(entList)-1].ID)))
			entList = entList[:len(entList)-1]
		}
		protoList, err := toProtoChannelList(entList)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return &ListChannelResponse{
			ChannelList:   protoList,
			NextPageToken: nextPageToken,
		}, nil
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// BatchCreate implements ChannelServiceServer.BatchCreate
func (svc *ChannelService) BatchCreate(ctx context.Context, req *BatchCreateChannelsRequest) (*BatchCreateChannelsResponse, error) {
	requests := req.GetRequests()
	if len(requests) > entproto.MaxBatchCreateSize {
		return nil, status.Errorf(codes.InvalidArgument, "batch size cannot be greater than %d", entproto.MaxBatchCreateSize)
	}
	bulk := make([]*ent.ChannelCreate, len(requests))
	for i, req := range requests {
		channel := req.GetChannel()
		var err error
		bulk[i], err = svc.createBuilder(channel)
		if err != nil {
			return nil, err
		}
	}
	res, err := svc.client.Channel.CreateBulk(bulk...).Save(ctx)
	switch {
	case err == nil:
		protoList, err := toProtoChannelList(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return &BatchCreateChannelsResponse{
			Channels: protoList,
		}, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

func (svc *ChannelService) createBuilder(channel *Channel) (*ent.ChannelCreate, error) {
	m := svc.client.Channel.Create()
	channelChannelID := channel.GetChannelId()
	m.SetChannelID(channelChannelID)
	channelDisplayName := channel.GetDisplayName()
	m.SetDisplayName(channelDisplayName)
	channelHandle := channel.GetHandle()
	m.SetHandle(channelHandle)
	channelThumbnailURL := channel.GetThumbnailUrl()
	m.SetThumbnailURL(channelThumbnailURL)
	for _, item := range channel.GetVideos() {
		videos := item.GetId()
		m.AddVideoIDs(videos)
	}
	return m, nil
}
