services:
  dogtrot:
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
      - '2345:2345'
    tty: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env
    networks:
      - default
  mysql:
    image: mysql:latest
    container_name: ${MYSQL_CONTAINER_NAME}
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - type: bind
        source: mysql-data
        target: /var/lib/mysql
    restart: always
    networks:
        - pdog-shared
        - default

volumes:
    mysql-data:

networks:
  pdog-shared:
    external: true