services:
  dogtrot:
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
      - '2345:2345'
    tty: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - .:/app
    restart: always