-- Create Index on "description" table
CREATE INDEX 'description_periodic_idx' ON 'description' ('periodic_id');
CREATE INDEX 'description_category_idx' ON 'description' ('category_id');
-- Create Index on "description_changes" table
CREATE INDEX 'description_changes_description_idx' ON 'description_changes' ('description_id');
-- Create Index on "video_title_changes" table
CREATE INDEX 'video_title_changes_video_idx' ON 'video_title_changes' ('video_id');
-- Create Index on "video_play_ranges" table
CREATE INDEX 'video_play_ranges_video_idx' ON 'video_play_ranges' ('video_id');
-- Create Index on "video_disallow_ranges" table
CREATE INDEX 'video_disallow_ranges_video_idx' ON 'video_disallow_ranges' ('video_id');
-- Create Index on "pat_chats" table
CREATE INDEX 'pat_chats_video_idx' ON 'pat_chats' ('video_id');