// Code generated by ent, DO NOT EDIT.

package pat_chat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/predicate"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/schema/pulid"
)

// ID filters vertices based on their ID field.
func ID(id pulid.ID) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id pulid.ID) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id pulid.ID) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...pulid.ID) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...pulid.ID) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id pulid.ID) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id pulid.ID) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id pulid.ID) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id pulid.ID) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldLTE(FieldID, id))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEQ(FieldMessage, v))
}

// Magnitude applies equality check predicate on the "magnitude" field. It's identical to MagnitudeEQ.
func Magnitude(v float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEQ(FieldMagnitude, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEQ(FieldScore, v))
}

// IsNegative applies equality check predicate on the "is_negative" field. It's identical to IsNegativeEQ.
func IsNegative(v bool) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEQ(FieldIsNegative, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEQ(FieldPublishedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEQ(FieldCreatedAt, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldContainsFold(FieldMessage, v))
}

// MagnitudeEQ applies the EQ predicate on the "magnitude" field.
func MagnitudeEQ(v float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEQ(FieldMagnitude, v))
}

// MagnitudeNEQ applies the NEQ predicate on the "magnitude" field.
func MagnitudeNEQ(v float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldNEQ(FieldMagnitude, v))
}

// MagnitudeIn applies the In predicate on the "magnitude" field.
func MagnitudeIn(vs ...float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldIn(FieldMagnitude, vs...))
}

// MagnitudeNotIn applies the NotIn predicate on the "magnitude" field.
func MagnitudeNotIn(vs ...float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldNotIn(FieldMagnitude, vs...))
}

// MagnitudeGT applies the GT predicate on the "magnitude" field.
func MagnitudeGT(v float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldGT(FieldMagnitude, v))
}

// MagnitudeGTE applies the GTE predicate on the "magnitude" field.
func MagnitudeGTE(v float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldGTE(FieldMagnitude, v))
}

// MagnitudeLT applies the LT predicate on the "magnitude" field.
func MagnitudeLT(v float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldLT(FieldMagnitude, v))
}

// MagnitudeLTE applies the LTE predicate on the "magnitude" field.
func MagnitudeLTE(v float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldLTE(FieldMagnitude, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v float64) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldLTE(FieldScore, v))
}

// IsNegativeEQ applies the EQ predicate on the "is_negative" field.
func IsNegativeEQ(v bool) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEQ(FieldIsNegative, v))
}

// IsNegativeNEQ applies the NEQ predicate on the "is_negative" field.
func IsNegativeNEQ(v bool) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldNEQ(FieldIsNegative, v))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldLTE(FieldPublishedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Pat_chat {
	return predicate.Pat_chat(sql.FieldLTE(FieldCreatedAt, v))
}

// HasVideo applies the HasEdge predicate on the "video" edge.
func HasVideo() predicate.Pat_chat {
	return predicate.Pat_chat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, VideoTable, VideoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVideoWith applies the HasEdge predicate on the "video" edge with a given conditions (other predicates).
func HasVideoWith(preds ...predicate.Video) predicate.Pat_chat {
	return predicate.Pat_chat(func(s *sql.Selector) {
		step := newVideoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Pat_chat) predicate.Pat_chat {
	return predicate.Pat_chat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Pat_chat) predicate.Pat_chat {
	return predicate.Pat_chat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Pat_chat) predicate.Pat_chat {
	return predicate.Pat_chat(sql.NotPredicates(p))
}
