// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/categorydescriptiontemplate"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/description"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/predicate"
)

// CategoryDescriptionTemplateQuery is the builder for querying CategoryDescriptionTemplate entities.
type CategoryDescriptionTemplateQuery struct {
	config
	ctx              *QueryContext
	order            []categorydescriptiontemplate.OrderOption
	inters           []Interceptor
	predicates       []predicate.CategoryDescriptionTemplate
	withDescriptions *DescriptionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CategoryDescriptionTemplateQuery builder.
func (cdtq *CategoryDescriptionTemplateQuery) Where(ps ...predicate.CategoryDescriptionTemplate) *CategoryDescriptionTemplateQuery {
	cdtq.predicates = append(cdtq.predicates, ps...)
	return cdtq
}

// Limit the number of records to be returned by this query.
func (cdtq *CategoryDescriptionTemplateQuery) Limit(limit int) *CategoryDescriptionTemplateQuery {
	cdtq.ctx.Limit = &limit
	return cdtq
}

// Offset to start from.
func (cdtq *CategoryDescriptionTemplateQuery) Offset(offset int) *CategoryDescriptionTemplateQuery {
	cdtq.ctx.Offset = &offset
	return cdtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cdtq *CategoryDescriptionTemplateQuery) Unique(unique bool) *CategoryDescriptionTemplateQuery {
	cdtq.ctx.Unique = &unique
	return cdtq
}

// Order specifies how the records should be ordered.
func (cdtq *CategoryDescriptionTemplateQuery) Order(o ...categorydescriptiontemplate.OrderOption) *CategoryDescriptionTemplateQuery {
	cdtq.order = append(cdtq.order, o...)
	return cdtq
}

// QueryDescriptions chains the current query on the "descriptions" edge.
func (cdtq *CategoryDescriptionTemplateQuery) QueryDescriptions() *DescriptionQuery {
	query := (&DescriptionClient{config: cdtq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cdtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cdtq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(categorydescriptiontemplate.Table, categorydescriptiontemplate.FieldID, selector),
			sqlgraph.To(description.Table, description.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, categorydescriptiontemplate.DescriptionsTable, categorydescriptiontemplate.DescriptionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(cdtq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CategoryDescriptionTemplate entity from the query.
// Returns a *NotFoundError when no CategoryDescriptionTemplate was found.
func (cdtq *CategoryDescriptionTemplateQuery) First(ctx context.Context) (*CategoryDescriptionTemplate, error) {
	nodes, err := cdtq.Limit(1).All(setContextOp(ctx, cdtq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{categorydescriptiontemplate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cdtq *CategoryDescriptionTemplateQuery) FirstX(ctx context.Context) *CategoryDescriptionTemplate {
	node, err := cdtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CategoryDescriptionTemplate ID from the query.
// Returns a *NotFoundError when no CategoryDescriptionTemplate ID was found.
func (cdtq *CategoryDescriptionTemplateQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = cdtq.Limit(1).IDs(setContextOp(ctx, cdtq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{categorydescriptiontemplate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cdtq *CategoryDescriptionTemplateQuery) FirstIDX(ctx context.Context) string {
	id, err := cdtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CategoryDescriptionTemplate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CategoryDescriptionTemplate entity is found.
// Returns a *NotFoundError when no CategoryDescriptionTemplate entities are found.
func (cdtq *CategoryDescriptionTemplateQuery) Only(ctx context.Context) (*CategoryDescriptionTemplate, error) {
	nodes, err := cdtq.Limit(2).All(setContextOp(ctx, cdtq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{categorydescriptiontemplate.Label}
	default:
		return nil, &NotSingularError{categorydescriptiontemplate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cdtq *CategoryDescriptionTemplateQuery) OnlyX(ctx context.Context) *CategoryDescriptionTemplate {
	node, err := cdtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CategoryDescriptionTemplate ID in the query.
// Returns a *NotSingularError when more than one CategoryDescriptionTemplate ID is found.
// Returns a *NotFoundError when no entities are found.
func (cdtq *CategoryDescriptionTemplateQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = cdtq.Limit(2).IDs(setContextOp(ctx, cdtq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{categorydescriptiontemplate.Label}
	default:
		err = &NotSingularError{categorydescriptiontemplate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cdtq *CategoryDescriptionTemplateQuery) OnlyIDX(ctx context.Context) string {
	id, err := cdtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CategoryDescriptionTemplates.
func (cdtq *CategoryDescriptionTemplateQuery) All(ctx context.Context) ([]*CategoryDescriptionTemplate, error) {
	ctx = setContextOp(ctx, cdtq.ctx, "All")
	if err := cdtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CategoryDescriptionTemplate, *CategoryDescriptionTemplateQuery]()
	return withInterceptors[[]*CategoryDescriptionTemplate](ctx, cdtq, qr, cdtq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cdtq *CategoryDescriptionTemplateQuery) AllX(ctx context.Context) []*CategoryDescriptionTemplate {
	nodes, err := cdtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CategoryDescriptionTemplate IDs.
func (cdtq *CategoryDescriptionTemplateQuery) IDs(ctx context.Context) (ids []string, err error) {
	if cdtq.ctx.Unique == nil && cdtq.path != nil {
		cdtq.Unique(true)
	}
	ctx = setContextOp(ctx, cdtq.ctx, "IDs")
	if err = cdtq.Select(categorydescriptiontemplate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cdtq *CategoryDescriptionTemplateQuery) IDsX(ctx context.Context) []string {
	ids, err := cdtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cdtq *CategoryDescriptionTemplateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cdtq.ctx, "Count")
	if err := cdtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cdtq, querierCount[*CategoryDescriptionTemplateQuery](), cdtq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cdtq *CategoryDescriptionTemplateQuery) CountX(ctx context.Context) int {
	count, err := cdtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cdtq *CategoryDescriptionTemplateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cdtq.ctx, "Exist")
	switch _, err := cdtq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cdtq *CategoryDescriptionTemplateQuery) ExistX(ctx context.Context) bool {
	exist, err := cdtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CategoryDescriptionTemplateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cdtq *CategoryDescriptionTemplateQuery) Clone() *CategoryDescriptionTemplateQuery {
	if cdtq == nil {
		return nil
	}
	return &CategoryDescriptionTemplateQuery{
		config:           cdtq.config,
		ctx:              cdtq.ctx.Clone(),
		order:            append([]categorydescriptiontemplate.OrderOption{}, cdtq.order...),
		inters:           append([]Interceptor{}, cdtq.inters...),
		predicates:       append([]predicate.CategoryDescriptionTemplate{}, cdtq.predicates...),
		withDescriptions: cdtq.withDescriptions.Clone(),
		// clone intermediate query.
		sql:  cdtq.sql.Clone(),
		path: cdtq.path,
	}
}

// WithDescriptions tells the query-builder to eager-load the nodes that are connected to
// the "descriptions" edge. The optional arguments are used to configure the query builder of the edge.
func (cdtq *CategoryDescriptionTemplateQuery) WithDescriptions(opts ...func(*DescriptionQuery)) *CategoryDescriptionTemplateQuery {
	query := (&DescriptionClient{config: cdtq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cdtq.withDescriptions = query
	return cdtq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Text string `json:"text,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CategoryDescriptionTemplate.Query().
//		GroupBy(categorydescriptiontemplate.FieldText).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cdtq *CategoryDescriptionTemplateQuery) GroupBy(field string, fields ...string) *CategoryDescriptionTemplateGroupBy {
	cdtq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CategoryDescriptionTemplateGroupBy{build: cdtq}
	grbuild.flds = &cdtq.ctx.Fields
	grbuild.label = categorydescriptiontemplate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Text string `json:"text,omitempty"`
//	}
//
//	client.CategoryDescriptionTemplate.Query().
//		Select(categorydescriptiontemplate.FieldText).
//		Scan(ctx, &v)
func (cdtq *CategoryDescriptionTemplateQuery) Select(fields ...string) *CategoryDescriptionTemplateSelect {
	cdtq.ctx.Fields = append(cdtq.ctx.Fields, fields...)
	sbuild := &CategoryDescriptionTemplateSelect{CategoryDescriptionTemplateQuery: cdtq}
	sbuild.label = categorydescriptiontemplate.Label
	sbuild.flds, sbuild.scan = &cdtq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CategoryDescriptionTemplateSelect configured with the given aggregations.
func (cdtq *CategoryDescriptionTemplateQuery) Aggregate(fns ...AggregateFunc) *CategoryDescriptionTemplateSelect {
	return cdtq.Select().Aggregate(fns...)
}

func (cdtq *CategoryDescriptionTemplateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cdtq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cdtq); err != nil {
				return err
			}
		}
	}
	for _, f := range cdtq.ctx.Fields {
		if !categorydescriptiontemplate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cdtq.path != nil {
		prev, err := cdtq.path(ctx)
		if err != nil {
			return err
		}
		cdtq.sql = prev
	}
	return nil
}

func (cdtq *CategoryDescriptionTemplateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CategoryDescriptionTemplate, error) {
	var (
		nodes       = []*CategoryDescriptionTemplate{}
		_spec       = cdtq.querySpec()
		loadedTypes = [1]bool{
			cdtq.withDescriptions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CategoryDescriptionTemplate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CategoryDescriptionTemplate{config: cdtq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cdtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cdtq.withDescriptions; query != nil {
		if err := cdtq.loadDescriptions(ctx, query, nodes,
			func(n *CategoryDescriptionTemplate) { n.Edges.Descriptions = []*Description{} },
			func(n *CategoryDescriptionTemplate, e *Description) {
				n.Edges.Descriptions = append(n.Edges.Descriptions, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cdtq *CategoryDescriptionTemplateQuery) loadDescriptions(ctx context.Context, query *DescriptionQuery, nodes []*CategoryDescriptionTemplate, init func(*CategoryDescriptionTemplate), assign func(*CategoryDescriptionTemplate, *Description)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*CategoryDescriptionTemplate)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Description(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(categorydescriptiontemplate.DescriptionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.category_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "category_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "category_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cdtq *CategoryDescriptionTemplateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cdtq.querySpec()
	_spec.Node.Columns = cdtq.ctx.Fields
	if len(cdtq.ctx.Fields) > 0 {
		_spec.Unique = cdtq.ctx.Unique != nil && *cdtq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cdtq.driver, _spec)
}

func (cdtq *CategoryDescriptionTemplateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(categorydescriptiontemplate.Table, categorydescriptiontemplate.Columns, sqlgraph.NewFieldSpec(categorydescriptiontemplate.FieldID, field.TypeString))
	_spec.From = cdtq.sql
	if unique := cdtq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cdtq.path != nil {
		_spec.Unique = true
	}
	if fields := cdtq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, categorydescriptiontemplate.FieldID)
		for i := range fields {
			if fields[i] != categorydescriptiontemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cdtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cdtq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cdtq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cdtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cdtq *CategoryDescriptionTemplateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cdtq.driver.Dialect())
	t1 := builder.Table(categorydescriptiontemplate.Table)
	columns := cdtq.ctx.Fields
	if len(columns) == 0 {
		columns = categorydescriptiontemplate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cdtq.sql != nil {
		selector = cdtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cdtq.ctx.Unique != nil && *cdtq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cdtq.predicates {
		p(selector)
	}
	for _, p := range cdtq.order {
		p(selector)
	}
	if offset := cdtq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cdtq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CategoryDescriptionTemplateGroupBy is the group-by builder for CategoryDescriptionTemplate entities.
type CategoryDescriptionTemplateGroupBy struct {
	selector
	build *CategoryDescriptionTemplateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cdtgb *CategoryDescriptionTemplateGroupBy) Aggregate(fns ...AggregateFunc) *CategoryDescriptionTemplateGroupBy {
	cdtgb.fns = append(cdtgb.fns, fns...)
	return cdtgb
}

// Scan applies the selector query and scans the result into the given value.
func (cdtgb *CategoryDescriptionTemplateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cdtgb.build.ctx, "GroupBy")
	if err := cdtgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CategoryDescriptionTemplateQuery, *CategoryDescriptionTemplateGroupBy](ctx, cdtgb.build, cdtgb, cdtgb.build.inters, v)
}

func (cdtgb *CategoryDescriptionTemplateGroupBy) sqlScan(ctx context.Context, root *CategoryDescriptionTemplateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cdtgb.fns))
	for _, fn := range cdtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cdtgb.flds)+len(cdtgb.fns))
		for _, f := range *cdtgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cdtgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cdtgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CategoryDescriptionTemplateSelect is the builder for selecting fields of CategoryDescriptionTemplate entities.
type CategoryDescriptionTemplateSelect struct {
	*CategoryDescriptionTemplateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cdts *CategoryDescriptionTemplateSelect) Aggregate(fns ...AggregateFunc) *CategoryDescriptionTemplateSelect {
	cdts.fns = append(cdts.fns, fns...)
	return cdts
}

// Scan applies the selector query and scans the result into the given value.
func (cdts *CategoryDescriptionTemplateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cdts.ctx, "Select")
	if err := cdts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CategoryDescriptionTemplateQuery, *CategoryDescriptionTemplateSelect](ctx, cdts.CategoryDescriptionTemplateQuery, cdts, cdts.inters, v)
}

func (cdts *CategoryDescriptionTemplateSelect) sqlScan(ctx context.Context, root *CategoryDescriptionTemplateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cdts.fns))
	for _, fn := range cdts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cdts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cdts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
