// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/description_change"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/predicate"
)

// DescriptionChangeDelete is the builder for deleting a Description_change entity.
type DescriptionChangeDelete struct {
	config
	hooks    []Hook
	mutation *DescriptionChangeMutation
}

// Where appends a list predicates to the DescriptionChangeDelete builder.
func (dcd *DescriptionChangeDelete) Where(ps ...predicate.Description_change) *DescriptionChangeDelete {
	dcd.mutation.Where(ps...)
	return dcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dcd *DescriptionChangeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dcd.sqlExec, dcd.mutation, dcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dcd *DescriptionChangeDelete) ExecX(ctx context.Context) int {
	n, err := dcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dcd *DescriptionChangeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(description_change.Table, sqlgraph.NewFieldSpec(description_change.FieldID, field.TypeString))
	if ps := dcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dcd.mutation.done = true
	return affected, err
}

// DescriptionChangeDeleteOne is the builder for deleting a single Description_change entity.
type DescriptionChangeDeleteOne struct {
	dcd *DescriptionChangeDelete
}

// Where appends a list predicates to the DescriptionChangeDelete builder.
func (dcdo *DescriptionChangeDeleteOne) Where(ps ...predicate.Description_change) *DescriptionChangeDeleteOne {
	dcdo.dcd.mutation.Where(ps...)
	return dcdo
}

// Exec executes the deletion query.
func (dcdo *DescriptionChangeDeleteOne) Exec(ctx context.Context) error {
	n, err := dcdo.dcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{description_change.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dcdo *DescriptionChangeDeleteOne) ExecX(ctx context.Context) {
	if err := dcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
