// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/categorydescriptiontemplate"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/channel"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/description"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/descriptionchange"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/patchat"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/periodicdescriptiontemplate"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/schema"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/video"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/videodisallowrange"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/videoplayrange"
	"github.com/KasumiMercury/uo-patradb-dogtrot/ent/videotitlechange"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categorydescriptiontemplateMixin := schema.CategoryDescriptionTemplate{}.Mixin()
	categorydescriptiontemplateMixinFields0 := categorydescriptiontemplateMixin[0].Fields()
	_ = categorydescriptiontemplateMixinFields0
	categorydescriptiontemplateFields := schema.CategoryDescriptionTemplate{}.Fields()
	_ = categorydescriptiontemplateFields
	// categorydescriptiontemplateDescID is the schema descriptor for id field.
	categorydescriptiontemplateDescID := categorydescriptiontemplateMixinFields0[0].Descriptor()
	// categorydescriptiontemplate.DefaultID holds the default value on creation for the id field.
	categorydescriptiontemplate.DefaultID = categorydescriptiontemplateDescID.Default.(func() string)
	channelMixin := schema.Channel{}.Mixin()
	channelMixinFields0 := channelMixin[0].Fields()
	_ = channelMixinFields0
	channelFields := schema.Channel{}.Fields()
	_ = channelFields
	// channelDescID is the schema descriptor for id field.
	channelDescID := channelMixinFields0[0].Descriptor()
	// channel.DefaultID holds the default value on creation for the id field.
	channel.DefaultID = channelDescID.Default.(func() string)
	descriptionMixin := schema.Description{}.Mixin()
	descriptionMixinFields0 := descriptionMixin[0].Fields()
	_ = descriptionMixinFields0
	descriptionFields := schema.Description{}.Fields()
	_ = descriptionFields
	// descriptionDescCreatedAt is the schema descriptor for created_at field.
	descriptionDescCreatedAt := descriptionFields[3].Descriptor()
	// description.DefaultCreatedAt holds the default value on creation for the created_at field.
	description.DefaultCreatedAt = descriptionDescCreatedAt.Default.(func() time.Time)
	// descriptionDescUpdatedAt is the schema descriptor for updated_at field.
	descriptionDescUpdatedAt := descriptionFields[4].Descriptor()
	// description.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	description.DefaultUpdatedAt = descriptionDescUpdatedAt.Default.(func() time.Time)
	// description.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	description.UpdateDefaultUpdatedAt = descriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// descriptionDescID is the schema descriptor for id field.
	descriptionDescID := descriptionMixinFields0[0].Descriptor()
	// description.DefaultID holds the default value on creation for the id field.
	description.DefaultID = descriptionDescID.Default.(func() string)
	descriptionchangeMixin := schema.DescriptionChange{}.Mixin()
	descriptionchangeMixinFields0 := descriptionchangeMixin[0].Fields()
	_ = descriptionchangeMixinFields0
	descriptionchangeFields := schema.DescriptionChange{}.Fields()
	_ = descriptionchangeFields
	// descriptionchangeDescChangedAt is the schema descriptor for changed_at field.
	descriptionchangeDescChangedAt := descriptionchangeFields[3].Descriptor()
	// descriptionchange.DefaultChangedAt holds the default value on creation for the changed_at field.
	descriptionchange.DefaultChangedAt = descriptionchangeDescChangedAt.Default.(func() time.Time)
	// descriptionchangeDescID is the schema descriptor for id field.
	descriptionchangeDescID := descriptionchangeMixinFields0[0].Descriptor()
	// descriptionchange.DefaultID holds the default value on creation for the id field.
	descriptionchange.DefaultID = descriptionchangeDescID.Default.(func() string)
	patchatMixin := schema.PatChat{}.Mixin()
	patchatMixinFields0 := patchatMixin[0].Fields()
	_ = patchatMixinFields0
	patchatFields := schema.PatChat{}.Fields()
	_ = patchatFields
	// patchatDescIsNegative is the schema descriptor for is_negative field.
	patchatDescIsNegative := patchatFields[3].Descriptor()
	// patchat.DefaultIsNegative holds the default value on creation for the is_negative field.
	patchat.DefaultIsNegative = patchatDescIsNegative.Default.(bool)
	// patchatDescCreatedAt is the schema descriptor for created_at field.
	patchatDescCreatedAt := patchatFields[5].Descriptor()
	// patchat.DefaultCreatedAt holds the default value on creation for the created_at field.
	patchat.DefaultCreatedAt = patchatDescCreatedAt.Default.(func() time.Time)
	// patchatDescID is the schema descriptor for id field.
	patchatDescID := patchatMixinFields0[0].Descriptor()
	// patchat.DefaultID holds the default value on creation for the id field.
	patchat.DefaultID = patchatDescID.Default.(func() string)
	periodicdescriptiontemplateMixin := schema.PeriodicDescriptionTemplate{}.Mixin()
	periodicdescriptiontemplateMixinFields0 := periodicdescriptiontemplateMixin[0].Fields()
	_ = periodicdescriptiontemplateMixinFields0
	periodicdescriptiontemplateFields := schema.PeriodicDescriptionTemplate{}.Fields()
	_ = periodicdescriptiontemplateFields
	// periodicdescriptiontemplateDescID is the schema descriptor for id field.
	periodicdescriptiontemplateDescID := periodicdescriptiontemplateMixinFields0[0].Descriptor()
	// periodicdescriptiontemplate.DefaultID holds the default value on creation for the id field.
	periodicdescriptiontemplate.DefaultID = periodicdescriptiontemplateDescID.Default.(func() string)
	videoMixin := schema.Video{}.Mixin()
	videoMixinFields0 := videoMixin[0].Fields()
	_ = videoMixinFields0
	videoFields := schema.Video{}.Fields()
	_ = videoFields
	// videoDescHasTimeRange is the schema descriptor for has_time_range field.
	videoDescHasTimeRange := videoFields[7].Descriptor()
	// video.DefaultHasTimeRange holds the default value on creation for the has_time_range field.
	video.DefaultHasTimeRange = videoDescHasTimeRange.Default.(bool)
	// videoDescCreatedAt is the schema descriptor for created_at field.
	videoDescCreatedAt := videoFields[11].Descriptor()
	// video.DefaultCreatedAt holds the default value on creation for the created_at field.
	video.DefaultCreatedAt = videoDescCreatedAt.Default.(func() time.Time)
	// videoDescUpdatedAt is the schema descriptor for updated_at field.
	videoDescUpdatedAt := videoFields[12].Descriptor()
	// video.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	video.DefaultUpdatedAt = videoDescUpdatedAt.Default.(func() time.Time)
	// video.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	video.UpdateDefaultUpdatedAt = videoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// videoDescID is the schema descriptor for id field.
	videoDescID := videoMixinFields0[0].Descriptor()
	// video.DefaultID holds the default value on creation for the id field.
	video.DefaultID = videoDescID.Default.(func() string)
	videodisallowrangeMixin := schema.VideoDisallowRange{}.Mixin()
	videodisallowrangeMixinFields0 := videodisallowrangeMixin[0].Fields()
	_ = videodisallowrangeMixinFields0
	videodisallowrangeFields := schema.VideoDisallowRange{}.Fields()
	_ = videodisallowrangeFields
	// videodisallowrangeDescID is the schema descriptor for id field.
	videodisallowrangeDescID := videodisallowrangeMixinFields0[0].Descriptor()
	// videodisallowrange.DefaultID holds the default value on creation for the id field.
	videodisallowrange.DefaultID = videodisallowrangeDescID.Default.(func() string)
	videoplayrangeMixin := schema.VideoPlayRange{}.Mixin()
	videoplayrangeMixinFields0 := videoplayrangeMixin[0].Fields()
	_ = videoplayrangeMixinFields0
	videoplayrangeFields := schema.VideoPlayRange{}.Fields()
	_ = videoplayrangeFields
	// videoplayrangeDescStartSeconds is the schema descriptor for start_seconds field.
	videoplayrangeDescStartSeconds := videoplayrangeFields[0].Descriptor()
	// videoplayrange.DefaultStartSeconds holds the default value on creation for the start_seconds field.
	videoplayrange.DefaultStartSeconds = videoplayrangeDescStartSeconds.Default.(int)
	// videoplayrangeDescID is the schema descriptor for id field.
	videoplayrangeDescID := videoplayrangeMixinFields0[0].Descriptor()
	// videoplayrange.DefaultID holds the default value on creation for the id field.
	videoplayrange.DefaultID = videoplayrangeDescID.Default.(func() string)
	videotitlechangeMixin := schema.VideoTitleChange{}.Mixin()
	videotitlechangeMixinFields0 := videotitlechangeMixin[0].Fields()
	_ = videotitlechangeMixinFields0
	videotitlechangeFields := schema.VideoTitleChange{}.Fields()
	_ = videotitlechangeFields
	// videotitlechangeDescChangedAt is the schema descriptor for changed_at field.
	videotitlechangeDescChangedAt := videotitlechangeFields[2].Descriptor()
	// videotitlechange.DefaultChangedAt holds the default value on creation for the changed_at field.
	videotitlechange.DefaultChangedAt = videotitlechangeDescChangedAt.Default.(func() time.Time)
	// videotitlechangeDescID is the schema descriptor for id field.
	videotitlechangeDescID := videotitlechangeMixinFields0[0].Descriptor()
	// videotitlechange.DefaultID holds the default value on creation for the id field.
	videotitlechange.DefaultID = videotitlechangeDescID.Default.(func() string)
}
