// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category_description_template is the predicate function for category_description_template builders.
type Category_description_template func(*sql.Selector)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// Description is the predicate function for description builders.
type Description func(*sql.Selector)

// Description_change is the predicate function for description_change builders.
type Description_change func(*sql.Selector)

// Periodic_description_template is the predicate function for periodic_description_template builders.
type Periodic_description_template func(*sql.Selector)

// Video is the predicate function for video builders.
type Video func(*sql.Selector)

// Video_disallow_range is the predicate function for video_disallow_range builders.
type Video_disallow_range func(*sql.Selector)

// Video_play_range is the predicate function for video_play_range builders.
type Video_play_range func(*sql.Selector)

// Video_title_change is the predicate function for video_title_change builders.
type Video_title_change func(*sql.Selector)
